Changed pos so it would display cutscene without freezing.
project-topaz/topaz pull request #1260
Opened 2020-10-05 19:28 UTC by nsabott

Changed the pos so that it leaves the character outside the instance afterwards, having it at <0, 0, 0, 0, zoneId) was causing issues with the cutscene displaying properly, it would freeze.

**_I affirm:_**
- [x] that I agree to Project Topaz's [Limited Contributor License Agreement](http://project-topaz.com/blob/release/CONTRIBUTOR_AGREEMENT.md), as written on this date
- [x] that I've _tested my code_ since the last commit in the PR, and will test after any later commits

2020-10-05 20:31 UTC, cocosolos commented on scripts/zones/Nyzul_Isle/instances/nashmeiras_plea.lua
> +        end
Is this cs supposed to play here? [This video](https://youtu.be/SLr-slWFjxQ?t=954) looks like its supposed to play when Alexander spawns.

2020-10-06 06:24 UTC, zach2good commented
If this was the fix to the black screen in this fight I'm going to lose my mind, it's the one thing I didn't try! 😆 

Please check your styling: 4 space indents, no tabs, etc.
https://github.com/project-topaz/topaz/blob/release/CONTRIBUTING.md#general-code-guidlines-all-languages

2020-10-10 06:07 UTC, zach2good requested changes
You might be barking up the right tree for how to fix this, but as it stands this PR doesn't work :(

2020-10-10 06:07 UTC, zach2good commented on scripts/zones/Nyzul_Isle/instances/nashmeiras_plea.lua
> +        end
Yeah, this moves the order of the CS to the end of the battle, instead of between phases.

2020-10-10 06:07 UTC, zach2good commented on scripts/zones/Nyzul_Isle/instances/nashmeiras_plea.lua
> +		v:setPos(126.6543, 0, 20.1798, 0, 72)
v isn't accessible until you're inside the loop

2020-10-10 06:07 UTC, zach2good commented on scripts/zones/Nyzul_Isle/instances/nashmeiras_plea.lua
> +			v:startEvent(203)
Be careful not to introduce full or half-tabs, only 4x spaces for indentation please

2020-10-11 17:46 UTC, closed without merging