fix(Newton Movalpolis): Link Furnace Hatch to all gates
project-topaz/topaz pull request #1421
Opened 2020-10-24 02:35 UTC by davismj

Each furnace hatch was only tied to its closest gate. This is not how the hatch works and it makes it impossible to traverse Newton Movalpolis to get to the Mine Shaft. Each furnace hatch should toggle all gates. This commit enforces that behavior.

Sources:
- https://web.archive.org/web/20070218171240/http://users.adelphia.net/~mithrankittycat/ffxi/movalpolos.png
- https://ffxi.allakhazam.com/db/areas.html?farea=147#m121595200841715177

**_I affirm:_**
- [x] that I agree to Project Topaz's [Limited Contributor License Agreement](http://project-topaz.com/blob/release/CONTRIBUTOR_AGREEMENT.md), as written on this date
- [] that I've _tested my code_ since the last commit in the PR, and will test after any later commits

2020-10-24 16:21 UTC, wrenffxi requested changes
Other than these recommended changes, PR does what it says and looks good to me.  Sorry for causing conflict in IDs.lua.

2020-10-24 16:21 UTC, wrenffxi commented on scripts/zones/Newton_Movalpolos/IDs.lua
> -        FURNACE_HATCH_OFFSET = 16826607,
This is still needed (see comment below)

2020-10-24 16:21 UTC, wrenffxi commented on scripts/zones/Newton_Movalpolos/npcs/Furnace_Hatch.lua
> -        local offset = npc:getID() - ID.npc.FURNACE_HATCH_OFFSET
offset is still needed to play the correct event (I think it's a short cutscene of your character toggling the lever) on line 13

2020-10-24 21:33 UTC, wrenffxi approved these changes

2020-10-28 05:50 UTC, zach2good commented
Don't worry about the CI, Ubuntu 18.04 and MariaDB 10.1 are apparently not friends anymore 🤷 

LGTM!

2020-10-28 05:50 UTC, merged