Adds scripts for some Temporary Items
project-topaz/topaz pull request #1434
Opened 2020-10-25 21:35 UTC by neuromancerxi

Adds Healing Salve I/II, Clear Salve I/II, Dusty Elixir

Lowered use timers from 4s to 1s (per bg wiki, 1s use time).
Clear Salve I can remove randomly up to two effects at random (https://translate.google.com/translate?hl=en&sl=ja&u=http://wiki.ffo.jp/html/20179.html&prev=search&pto=aue). Interpreted this to mean can remove between 1 and 2 effects.

**_I affirm:_**
- [x] that I agree to Project Topaz's [Limited Contributor License Agreement](http://project-topaz.com/blob/release/CONTRIBUTOR_AGREEMENT.md), as written on this date
- [x] that I've _tested my code_ since the last commit in the PR, and will test after any later commits

2020-10-26 08:24 UTC, zach2good requested changes
Content seems fine, just some style dings. I'm also 1000% sure there is a better way to do that big counting status effect section.
```lua
-- A util of some sort
tpz.utils.removeNStatusEffects = function(target, n_to_remove)
    local statusEffectTable = {...}
    local function removeStatus()
        for effect in statusEffectTable then
            if target:delStatusEffect(effect) then return true end
        end
        if target:eraseStatusEffect() ~= 255 then return true end
        return false
    end

    local removed = 0
    repeat
        if not removeStatus() then break end
        n_to_remove = n_to_remove - 1
        removed = removed + 1
    until (n_to_remove <= 0)

    return removed
end

...


local pet = target:getPet()
local removed = tpz.utils.removeNStatusEffects(pet, math.random(1, 2))
return removed
```

Something like this? I dunno

2020-10-26 08:24 UTC, zach2good commented on scripts/globals/items/tube_of_clear_salve_i.lua
> +    until (toremove <= 0)
Ohhhh I didn't know Lua had repeat/until (do/while)!

2020-10-26 08:24 UTC, zach2good commented on scripts/globals/items/tube_of_clear_salve_ii.lua
> +    if (not target:hasPet()) then
No need for these braces:
https://github.com/project-topaz/topaz/blob/release/CONTRIBUTING.md#no-parentheses-unless-needed-to-clarify-order-of-operations

2020-10-26 08:24 UTC, zach2good commented on scripts/globals/items/dusty_elixir.lua
> +    if (mHP == cHP and mMP == cMP) then
https://github.com/project-topaz/topaz/blob/release/CONTRIBUTING.md#no-parentheses-unless-needed-to-clarify-order-of-operations

2020-10-26 08:24 UTC, zach2good commented on scripts/globals/items/tube_of_clear_salve_i.lua
> +    end
I know this section probably exists somewhere else, but there _has_ to be a better way of doing this...

2020-10-26 08:24 UTC, zach2good commented on scripts/globals/items/tube_of_healing_salve_i.lua
> +    local totalHP = (pet:getMaxHP()/100)*percent
`local totalHP = (pet:getMaxHP() / 100) * percent`

2020-10-29 03:25 UTC, TeoTwawki commented on scripts/globals/items/tube_of_clear_salve_i.lua
> +    local effects = {
```lua
    local effects =
    {
        tpz.effect.PETRIFICATION,
        tpz.effect.SILENCE,
        tpz.effect.BANE,
        tpz.effect.CURSE_II,
        tpz.effect.CURSE_I,
        tpz.effect.PARALYSIS,
        tpz.effect.PLAGUE,
        tpz.effect.POISON,
        tpz.effect.DISEASE,
        tpz.effect.BLINDNESS
    }
```
to conform to the [style guide](https://github.com/project-topaz/topaz/blob/release/CONTRIBUTING.md#allman-braces)

2020-10-29 05:03 UTC, zach2good approved these changes

2020-10-29 05:03 UTC, merged