Desynths
project-topaz/topaz pull request #1447
Opened 2020-10-28 21:29 UTC by Dirk-Dieters

For this round, I used the following criteria:

1: Item has a specific desynth recipe and yield listed on its BGWiki page (without a level) AND Item has a synthesis recipe
2: Item was previously updated in level but not activated due to yield mismatch.

In cases where the item is craftable, but the desynth recipe had no level assigned to it, the level was set to match the synthesis level, and a comment was added in case future evidence proves that the level should be different.

In cases where the yield shown on FFXIAH/the current database were similar, but not exact matches, (More HQ result information on the BGWiki page primarily), the BGWiki data was used. This includes previously identified mismatched yields, and they have been activated as well.

Some notes: 
Apparently Desynths aren't a huge priority for the BGWiki contributors, especially smithing, we might have to accept data from FFXIclopedia or another source in order to resolve many of these.

I left comments on several still-disabled recipes that I was unsure about how to proceed.

**_I affirm:_**
- [X] that I agree to Project Topaz's [Limited Contributor License Agreement](http://project-topaz.com/blob/release/CONTRIBUTOR_AGREEMENT.md), as written on this date
- [X] that I've _tested my code_ since the last commit in the PR, and will test after any later commits

2020-10-29 18:34 UTC, ibm2431 commented
End of line comments are fine if there's a space after the `--`.
`-- This is fine`.
`--This upsets SQL.`

2020-10-29 18:44 UTC, Dirk-Dieters commented
I see, thanks

On Thu, Oct 29, 2020, 12:35 PM ibm2431 <notifications@github.com> wrote:

> End of line comments are fine if there's a space after the --.
> -- This is fine.
> --This upsets SQL.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/project-topaz/topaz/pull/1447#issuecomment-718943552>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AIRRVPO6UC6B3BEXCGXIOVTSNGYV3ANCNFSM4TC4QRCQ>
> .
>

2020-11-08 12:02 UTC, ibm2431 requested changes
Sorry this took me a bit to review!

Mostly okay, just a couple things I spotted.

I do appreciate someone taking the time to go through these and making the super safe changes! 🎉

2020-11-08 12:02 UTC, ibm2431 commented on sql/synth_recipes.sql
> +INSERT INTO `synth_recipes` VALUES (9906,1,0,102,0,0,0,0,0,0,0,4100,4242,17592,0,0,0,0,0,0,0,771,1228,1228,1225,1,4,4,4,'Kinkobo (desynth)'); -- Level based on level to synth
Let's adjust the HQ1 to Yellow Rock while we're here (Kinkobo).

2020-11-08 12:02 UTC, ibm2431 commented on sql/synth_recipes.sql
> +INSERT INTO `synth_recipes` VALUES (9921,1,0,51,0,0,0,0,0,0,0,4100,4242,17388,0,0,0,0,0,0,0,707,707,820,820,1,1,1,1,'Fastwater F. Rod (desynth)'); -- Level based on level to synth
51 is for the "restoral" to fix a broken rod; the synth recipe from the desynth ingredients  ingredients is 56~

2020-11-08 12:02 UTC, ibm2431 commented on sql/synth_recipes.sql
> +INSERT INTO `synth_recipes` VALUES (29901,1,0,0,0,55,0,0,0,0,0,4100,4242,13473,0,0,0,0,0,0,0,814,814,744,744,1,1,1,2,'Amber Ring (desynth)');
BGWiki is listing an earth crystal for the desynth, but I'm fairly certain we can reasonably ignore what was probably an editor copy-pasting from the synth table, and keep this lightning crystal instead.

2020-11-08 12:02 UTC, ibm2431 commented on sql/synth_recipes.sql
> +INSERT INTO `synth_recipes` VALUES (29907,1,0,0,0,55,0,0,0,0,0,4100,4242,13444,0,0,0,0,0,0,0,807,807,744,744,1,1,1,2,'Sardonyx Ring (desynth)');
BGWiki is claiming 35; Sardonyx is a STAT+1, not a STAT+2 like the Peridot and Sphene Rings before it in this cluster

2020-11-08 12:02 UTC, ibm2431 commented on sql/synth_recipes.sql
> +INSERT INTO `synth_recipes` VALUES (29908,1,0,0,0,55,0,0,0,0,0,4100,4242,13483,0,0,0,0,0,0,0,792,653,653,653,1,2,2,2,'Pearl Ring (desynth)');
We can correct the HQ yields while we're here:
```
Pearl,
Pearl,
Mythril Ingot
Mythril Ingot x2
```

2020-11-08 12:02 UTC, ibm2431 commented on sql/synth_recipes.sql
> +INSERT INTO `synth_recipes` VALUES (49933,1,0,0,0,0,0,255,0,0,0,4100,4242,13939,0,0,0,0,0,0,0,850,851,851,851,1,1,1,1,'Austere Hat (desynth)'); -- BG data incomplete but does not contradict
BGWiki does say a synth/desynth level of 93 though 😉

2020-11-08 12:02 UTC, ibm2431 commented on sql/synth_recipes.sql
> +INSERT INTO `synth_recipes` VALUES (49938,1,0,0,0,0,0,255,0,0,0,4100,4242,13203,0,0,0,0,0,0,0,850,924,924,924,1,1,1,1,'Barbarian\'s Belt (desynth)'); -- BG data incomplete but does not contradict
Has a level of 41 though~!

2020-11-08 12:02 UTC, ibm2431 commented on sql/synth_recipes.sql
> +INSERT INTO `synth_recipes` VALUES (59906,1,0,0,0,0,0,0,18,0,0,4100,4242,12454,0,0,0,0,0,0,0,880,880,850,8,1,1,1,1,'Bone Mask (desynth)');
I suspect you don't mean to have an HQ3 of Royal Bed coming out of this Bone Mask 😆

2020-11-09 02:37 UTC, Dirk-Dieters commented
Trying to figure out where to go from here, There's a lot of just baseline desynths that are still disabled, but can't be fully justified with only BGWiki and FFXIAH as sources. Do we start accepting FFXIclopedia? If so, do we take it for results, or just levels?

From what I understand, everything craftable should be desynthable at the same level as the craft, so I'll make that the goal of my next PR, but there's not justification for all those recepies on BGWiki, and we already know that FFXIAH doesn't have complete data, so I'll have to do verification from FFXIclopedia or another source.

2020-11-11 13:06 UTC, ibm2431 approved these changes
Kinkobo desynth's Yellow Rock HQ1 should be quantity 1, but I'll ninja-change that after merge so you don't need to wait longer on merge after a one line change. 😉

2020-11-11 13:09 UTC, merged