Implement "Tea With A Tonberry?"
project-topaz/topaz pull request #1450
Opened 2020-10-28 23:51 UTC by rude-jerk

**_I affirm:_**
- [x] that I agree to Project Topaz's [Limited Contributor License Agreement](http://project-topaz.com/blob/release/CONTRIBUTOR_AGREEMENT.md), as written on this date
- [x] that I've _tested my code_ since the last commit in the PR, and will test after any later commits

2020-10-31 09:42 UTC, zach2good requested changes
Content all seems fine, but there are a mix of tabs/half-tabs and spaces all over the place - 4x space for indents everywhere please 🙏

2020-10-31 15:14 UTC, rude-jerk commented
@zach2good Whoops, forgot to hit the code reformat button on things that were copied! 👎

2020-11-01 06:14 UTC, zach2good approved these changes

2020-11-01 06:15 UTC, merged

2020-11-01 06:17 UTC, zach2good commented
Since the rest of the PR was good and there was only one small style ding, I accepted it and ninja's the tweak in myself:
https://github.com/project-topaz/topaz/commit/9c6a335dc8ba5f04abada8b1d454b8eeb07d90ad

https://github.com/project-topaz/topaz/blob/release/CONTRIBUTING.md#formatting-conditional-blocks

Thanks again :)