Adds Combat/Magic Skill Gain MODs to associated items.
project-topaz/topaz pull request #1471
Opened 2020-11-03 03:29 UTC by neuromancerxi

All except Guide/Sprout are expected to be 1% gain based on JPWiki findings:

http://wiki.ffo.jp/html/24849.html
http://wiki.ffo.jp/html/24850.html
http://wiki.ffo.jp/html/23886.html

Corrected MOD typo in Vishap Armet/+1 that was discovered while adding MOD values.

**_I affirm:_**
- [x] that I agree to Project Topaz's [Limited Contributor License Agreement](http://project-topaz.com/blob/release/CONTRIBUTOR_AGREEMENT.md), as written on this date
- [x] that I've _tested my code_ since the last commit in the PR, and will test after any later commits

2020-11-03 05:09 UTC, TeoTwawki commented
Translatified links
https://translate.google.com/translate?sl=auto&tl=en&u=wiki.ffo.jp/html/24849.html
https://translate.google.com/translate?sl=auto&tl=en&u=wiki.ffo.jp/html/24850.html
https://translate.google.com/translate?sl=auto&tl=en&u=wiki.ffo.jp/html/23886.html

2020-11-03 05:13 UTC, TeoTwawki commented on sql/item_mods.sql
> +INSERT INTO `item_mods` VALUES (27676,108,15); -- Evasion+15
Modifier 108 is Evasion _skill_ and modifier 68 is actual evasion. You want 68.

![image](https://user-images.githubusercontent.com/6871475/97951743-3604fc00-1d69-11eb-983e-678d6ec3b970.png)

2020-11-03 05:13 UTC, TeoTwawki requested changes

2020-11-03 05:13 UTC, TeoTwawki commented on sql/item_mods.sql
> +INSERT INTO `item_mods` VALUES (27697,108,33); -- Evasion+33
mod 68

2020-11-03 15:52 UTC, TeoTwawki approved these changes

2020-11-04 05:24 UTC, zach2good approved these changes

2020-11-04 05:24 UTC, merged