adds missing currencies to show inside currency1 menu
project-topaz/topaz pull request #1501
Opened 2020-11-11 07:19 UTC by kaincenteno

Adds missing currencies inside Currency1 in both packet and sql db as of 10NOV2020
Also added migration script for existing servers to add those columns

Didn't add daily tally to the import as it already exists as a different file, but not for the sql import script or found in the currency1.cpp packet

This should help new members freaking out about having random numbers on their currencies. I will work on currency2 on an upcoming PR.

**_I affirm:_**
- [x] that I agree to Project Topaz's [Limited Contributor License Agreement](http://project-topaz.com/blob/release/CONTRIBUTOR_AGREEMENT.md), as written on this date
- [x] that I've _tested my code_ since the last commit in the PR, and will test after any later commits

2020-11-11 15:16 UTC, zach2good requested changes
All looks reasonable enough, will be ready to go once that missing comma and style issue are fixed 👍

2020-11-11 15:16 UTC, zach2good commented on tools/migrations/currency_columns.py
> +		print("Something went wrong: {}".format(err))
Newline at the end of this file please

2020-11-11 15:16 UTC, zach2good commented on sql/char_points.sql
> +  `daily_tally` int(5) signed NOT NULL DEFAULT '-1'
Missing a `,` at the end of this line

2020-11-11 20:38 UTC, kaincenteno commented
Changed sone @zach2good  =D

2020-11-13 06:13 UTC, zach2good approved these changes

2020-11-13 06:13 UTC, merged