FadedPromises Bastok Quest
project-topaz/topaz pull request #559
Opened 2020-05-01 05:44 UTC by hooksta4

**_I affirm:_**
- [x] that I agree to Project Topaz's [Limited Contributor License Agreement](http://project-topaz.com/blob/release/CONTRIBUTOR_AGREEMENT.md), as written on this date
- [x] that I've _tested my code_ since the last commit in the PR, and will test after any later commits

2020-05-01 06:06 UTC, kaincenteno commented
I just did this quest 2 months ago. What was changed?

2020-05-01 06:41 UTC, hooksta4 commented
Not sure, I didn't see any of the stuff for that in project-topaz:release

2020-05-01 06:50 UTC, kaincenteno commented
you are right, sorry for the confusion, disregard my comment

2020-05-01 07:29 UTC, hooksta4 commented
I was laying in bed and thought I had messed a var up and I did. I’ll update in the morning.

2020-05-07 09:31 UTC, ibm2431 requested changes
Yep, looks like your var got a little confused! 😉

2020-05-07 09:31 UTC, ibm2431 commented on scripts/zones/Port_Bastok/npcs/Kagetora.lua
> +    elseif (FadedPromises == QUEST_ACCEPTED and player:hasKeyItem(tpz.ki.DIARY_OF_MUKUNDA)) then
I'm guessing this is supposed to be checking for FadedPromises == 1...

2020-05-07 09:31 UTC, ibm2431 commented on scripts/zones/Metalworks/npcs/Ayame.lua
> +        player:setCharVar("FadedPromises",4)
..and then Ayame sets it to 3 in 804...

2020-05-07 09:31 UTC, ibm2431 commented on scripts/zones/Metalworks/npcs/Alois.lua
> +    elseif (player:getCharVar("FadedPromises") == 4) then
...And then the final check is for 3, right?

2020-05-07 09:31 UTC, ibm2431 commented on scripts/globals/treasure.lua
> +                        test = function(player) return player:getQuestStatus(BASTOK,tpz.quest.id.bastok.FADED_PROMISES) == QUEST_ACCEPTED and player:getCharVar("FadedPromises") == 2 and not player:ha
And that the test is for if the FadedPromises var is 1?

2020-05-07 12:44 UTC, hooksta4 commented
So that comment above that said "I was laying in bed and thought I had messed a var up and I did. I’ll update in the morning." Yea i forgot to update it. Here is the changes.

2020-05-07 22:35 UTC, ibm2431 approved these changes
Thanks, hooksta!

2020-05-07 22:36 UTC, merged