Update rolanberry_faifuku/+1
project-topaz/topaz pull request #579
Opened 2020-05-03 18:59 UTC by hooksta4

Updated mods based onhttps://www.bg-wiki.com/bg/Rolan._Daifuku and https://www.bg-wiki.com/bg/Rolan._Daifuku_%2B1

**_I affirm:_**
- [x] that I agree to Project Topaz's [Limited Contributor License Agreement](http://project-topaz.com/blob/release/CONTRIBUTOR_AGREEMENT.md), as written on this date
- [x] that I've _tested my code_ since the last commit in the PR, and will test after any later commits

2020-05-04 03:13 UTC, 59blargedy commented on scripts/globals/items/rolanberry_daifuku.lua
>      target:delPetMod(tpz.mod.VIT, 3)
add target:delPetMod(tpz.mod.DEX, 2)

2020-05-04 03:16 UTC, 59blargedy commented on scripts/globals/items/rolanberry_daifuku_+1.lua
> +	target:delPetMod(tpz.mod.DEX, 3)
spacing :)

2020-05-04 03:17 UTC, 59blargedy requested changes
i'm new to reviewing so hope the comments come through right. thank you for submitting, just needs those 2 changes.

2020-05-04 03:38 UTC, hooksta4 commented
Ha, that's what I get for rushing through it. Thanks! and the notes came through. 

Cheers

2020-05-04 07:31 UTC, 59blargedy approved these changes

2020-05-05 01:33 UTC, ghost approved these changes

2020-05-05 07:56 UTC, ibm2431 approved these changes

2020-05-05 07:56 UTC, merged