Bug with capped skills
project-topaz/topaz pull request #933
Opened 2020-08-09 09:26 UTC by jarmengaud

**_I affirm:_**
- [x] that I agree to Project Topaz's [Limited Contributor License Agreement](http://project-topaz.com/blob/release/CONTRIBUTOR_AGREEMENT.md), as written on this date
- [x] that I've _tested my code_ since the last commit in the PR, and will test after any later commits

Fixes https://github.com/project-topaz/topaz/issues/60

2020-08-09 12:40 UTC, zach2good requested changes
Looks good, just needs a tiny bit of cleanup. 

Fixing a bug is more important than 100% retail accuracy, but if you're here and you understand what's going on, getting this to be retail-accurate would be great. If not, open up a relevant issue when this is merged 👍

2020-08-09 12:40 UTC, zach2good commented on src/map/utils/charutils.cpp
>                  MaxSkill = MaxSkill * 10;
This isn't used any more at this point, can be removed

2020-08-09 12:40 UTC, zach2good commented on src/map/utils/charutils.cpp
> +            // Max skill this mob level will allow.
Would be clearer to say "victim" or "target" instead of "mob" here, that's how it's called from `attack.cpp` and `battleutils.cpp` etc.

2020-08-09 16:47 UTC, jarmengaud commented
I know that you can cap skill with decent challenge now, but I don't know the probability.
I would have difficulties trying to find the correct values from retail captures (besides i imagine it depends also on level, so would have to do several captures between 1 to 99...)
So i will just log an issue for the moment

2020-08-18 12:49 UTC, 59blargedy approved these changes

2020-08-19 14:37 UTC, merged