Pr sheep in antlions
project-topaz/topaz pull request #960
Opened 2020-08-16 16:21 UTC by m241dan

**_I affirm:_**
- [x] that I agree to Project Topaz's [Limited Contributor License Agreement](http://project-topaz.com/blob/release/CONTRIBUTOR_AGREEMENT.md), as written on this date
- [x] that I've _tested my code_ since the last commit in the PR, and will test after any later commits

2020-08-22 09:11 UTC, zach2good requested changes
Just one tiny gripe in terms of content/logic, needs some alignment/style fixes then this looks good to go! Nice work 👍

2020-08-22 09:11 UTC, zach2good commented on scripts/globals/mobskills/sand_pit.lua
> +	PoolID = mob:getPool()
Should this be local?

2020-08-22 09:11 UTC, zach2good commented on src/map/ai/controllers/mob_controller.cpp
> +            if (PMob->CanRest() && PMob->getMobMod(MOBMOD_NO_REST) == 0)
Good catch! I assume that only `CMobEntity` has access to `getMobMod` otherwise I'd say sling it inside `CBattleEntity::CanRest()`

2020-08-22 09:11 UTC, zach2good commented on scripts/zones/Boneyard_Gully/mobs/Tuchulcha.lua
> +function onMobFight(mob,target)
This function: beautifully aligned

2020-08-22 09:11 UTC, zach2good commented on scripts/zones/Boneyard_Gully/mobs/Swift_Hunter.lua
> +end
Please fix the alignment here

2020-08-22 09:11 UTC, zach2good commented on scripts/zones/Boneyard_Gully/mobs/Shrewd_Hunter.lua
> +	mob:setMobMod(tpz.mobMod.NO_MOVE, 1)
Please fix the alignment here

2020-08-22 09:11 UTC, zach2good commented on scripts/zones/Boneyard_Gully/mobs/Armored_Hunter.lua
> +	mob:setMobMod(tpz.mobMod.NO_MOVE, 1)
Please fix the alignment here

2020-08-22 09:11 UTC, zach2good commented on scripts/zones/Boneyard_Gully/bcnms/sheep_in_antlions_clothing.lua
> +	Tuchulcha:setLocalVar('sand_pit3', pos[6])
4-space alignment here please, otherwise very nice

2020-08-22 09:11 UTC, zach2good commented on scripts/zones/Boneyard_Gully/IDs.lua
> +            ARMORED_HUNTER_ID = 16810004,
Please align all of the IDs

2020-08-22 09:11 UTC, zach2good commented on scripts/globals/utils.lua
> +-- Generates a random permutation of integers >= min_val and <= max_val
Cool!

2020-08-22 13:38 UTC, m241dan commented on scripts/globals/mobskills/sand_pit.lua
> +	PoolID = mob:getPool()
yes

2020-08-22 13:39 UTC, m241dan commented on scripts/zones/Boneyard_Gully/mobs/Swift_Hunter.lua
> +end
ya, I'm starting to realize that CLion is not good at catching Lua spacing when my other devs are adding contributions and their IDE seems to be set to tabs. x.x

2020-08-22 13:42 UTC, zach2good commented on scripts/globals/mobskills/sand_pit.lua
> +	PoolID = mob:getPool()
Using my question as the example, maybe plop a comment here saying this is intended so nobody tries to "clean" it

2020-08-22 13:53 UTC, m241dan commented on scripts/globals/mobskills/sand_pit.lua
> +	PoolID = mob:getPool()
wait, what do you mean? It "should" be local (I added local, pushing soon).

2020-08-22 18:50 UTC, TeoTwawki commented on scripts/globals/utils.lua
> +    if (min_val >= max_val) then
outer parens not needed.

Also neat. whats this for? 
(as in whats this make possible/easier that our existing randoms and shuffle functionality can't do, coz looks like it was just used to random select positions)
not against it just want to understand better.

2020-08-22 19:04 UTC, m241dan commented on scripts/globals/utils.lua
> +    if (min_val >= max_val) then
WHY ARE YOU AGAINST THIS!?!?!?

just kidding

This ensures that if we roll random from 1 to 6, 6 times, we get 1 2 3 4 5 6 in any order with no repetitions, ie a permutation.

2020-08-23 01:34 UTC, TeoTwawki commented on scripts/globals/utils.lua
> +    if (min_val >= max_val) then
Today I learned when I permute it means I don’t roll the same number twice :+1:

2020-09-03 12:04 UTC, zach2good approved these changes
I've re-reviewed this and it looks good 👍 

If you resolve the conflict, I want to merge your BCNM/ENM work into a branch and get them into canary ASAP

2020-09-16 04:31 UTC, zach2good commented
```
Conflicting files
scripts/globals/status.lua
sql/mob_groups.sql
sql/mob_pools.sql
src/map/mob_modifier.h
```

I have royally boned this PR by merging master into `feature/enm`, I'm gonna close it and merge your branch directly into `feature/enm` (since it's approved) and resolve the conflicts myself - gotta make sure I keep your commits intact 'yo!

2020-09-16 04:31 UTC, closed without merging