Uragnite mixin
project-topaz/topaz pull request #989
Opened 2020-08-21 03:49 UTC by wrenffxi

**_I affirm:_**
- [x] that I agree to Project Topaz's [Limited Contributor License Agreement](http://project-topaz.com/blob/release/CONTRIBUTOR_AGREEMENT.md), as written on this date
- [x] that I've _tested my code_ since the last commit in the PR, and will test after any later commits

Creates uragnite mixin and applies to Coralline and Nightmare uragnites.  Mixin includes:

* shell mode, wherein uragnite
    * changes AnimationSub
    * ceases attacking or moving
    * takes greatly reduced damage
    * gains regen
    * uses shell skills
* physical attacks have a chance to push uragnite into shell mode
* uragnite leaves shell mode after some time
* an optional config function that lets you set custom values for most of these things

Fixes #985

2020-08-21 11:48 UTC, TeoTwawki approved these changes

2020-08-21 14:28 UTC, m241dan approved these changes
At a glance, this is very well implemented.

I am particularly fond of having the ability to configure the mixin for specific use; great work here.

I'm approving but did not take too deep of a dive in this.

2020-08-22 08:20 UTC, zach2good approved these changes
Looks good to me!

2020-08-22 14:17 UTC, m241dan requested changes
Actually, I was thinking about this the other night, and when are mixins loaded? On init? On spawn?

I believe this could cause an issue because local vars are zero'd on Spawn.

2020-08-22 15:10 UTC, zach2good commented
They are indeed zero'd OnSpawn

2020-08-22 17:59 UTC, TeoTwawki commented
right but that doesn't look like a problem here. the mixin is just changing them from the zero they start life with here `mob:addListener("SPAWN", "URAGNITE_SPAWN", function(mob)` and it doesn't look like anything relies on them being nonzero at spawntime before that. it would be pretty silly for us to have a spawn hook in the core that execs before the rest of the spawn code cleans out out vars and mods.

2020-08-22 18:05 UTC, m241dan approved these changes
> right but that doesn't look like a problem here. the mixin is just changing them from the zero they start life with here `mob:addListener("SPAWN", "URAGNITE_SPAWN", function(mob)` and it doesn't look like anything relies on them being nonzero at spawntime before that. it would be pretty silly for us to have a spawn hook in the core that execs before the rest of the spawn code cleans out out vars and mods.

Ahhh, after my 5th look, I see my mistake.

Sorry for the hold up @wrenffxi !

Back to approving!

2020-08-27 21:29 UTC, Wiggo32 approved these changes

2020-08-28 03:41 UTC, merged